"""
Django settings for ipfinder project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG")
# DEBUG = bool(int(os.environ.get('DEBUG', 0)))

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(
    filter(
        None,
        os.environ.get('ALLOWED_HOSTS', '').split(','),
    )
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ipfinder'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'filter': {
        'ENGINE': 'dj_db_conn_pool.backends.oracle',
        'POOL_OPTIONS': {
            'POOL_SIZE': 3,
            'MAX_OVERFLOW': 3},
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS')
    }
}

# Excel columns and rows settings for extracting values
# Column numbering starts from 0
# Row numbering starts from 1
EXCEL_ROW_COLUMN = {
    'default': {
        'Start_row': 2,
        'IP_DST': 4,
        'Port_DST': 5,
        'Date': 6,
        'Time': 7,
        'Provider': 8,
        'DST': 10,
    }
}

ORACLE_FUNCTIONS = {
    'tel_func': 'NEVA.ip_tr.restore_tel_from_ip_list',
    'inner_tel_func': 'NEVA.ip_tr.restore_tel_from_inner_ip_list'
}

OPERATORS = {
    '3Mob': '3MOB',
    'Vodafone': 'MTS',
    'UMC': 'MTS',
    'MTS': 'MTS',
    'VF-Ukraine': 'MTS',
    'VF UKRAINE': 'MTS',
    'KS': 'KS',
    'Kyivstar': 'KS',
    'Kyivstar UA': 'KS',
    'Kievstar': 'KS',
    'Kievstar GSM': 'KS',
    'lifecell': 'LIFE',
    'Lifecell': 'LIFE',
    'LifeCell': 'LIFE',
    'life': 'LIFE',
    'LIFE': 'LIFE',
    'LIFECELL': 'LIFE',
    'life:)': 'LIFE'
}

MOB3_IPS = ()
MTS_IPS = ('46.133', '89.209', '31.144', '128.124', '178.133')
KS_IPS = ('46.211', '94.153.112')
LIFE_IPS = ('37.73', '46.96', '88.154', '88.155')

# MOB3_INNER_IPS = (10, 37, 192)
# MTS_INNER_IPS = (10, 11, 100, 192)
# KS_INNER_IPS = (10, 11, 100, 111, 134, 188, 192, '2a02')
# LIFE_INNER_IPS = (10, 11, 100, 192)

# Output params:
# Excel result column name
DESTINATION_NUMBER = 'DST number'
RESULT_DIRECTORY = BASE_DIR / 'result'
EXCEL_OUTPUT_FILE_PREFIX = '_result'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# for development
STATICFILES_DIRS = [BASE_DIR / 'static']
# for deployment
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
